Traceback (most recent call last):
  File "C:\Users\bioinfo guru\.conda\envs\bio-env\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\bioinfo guru\.conda\envs\bio-env\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\bioinfo guru\.conda\envs\bio-env\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\bioinfo guru\.conda\envs\bio-env\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\bioinfo guru\.conda\envs\bio-env\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\bioinfo guru\.conda\envs\bio-env\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\bioinfo guru\.conda\envs\bio-env\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\bioinfo guru\.conda\envs\bio-env\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
cm = confusion_matrix(labels,clf_new_predict)
print(cm)

fig,ax= plt.subplots()
sns.heatmap(cm, square=True, annot=True, fmt='g', cbar=False, ax=ax)
ax.set_xlabel('Predicted labels')
ax.set_ylabel('True labels')
ax.xaxis.set_ticklabels(['positive', 'negative'])
ax.yaxis.set_ticklabels(['positive', 'negative'])
plt.show()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [17][0m, in [0;36m<cell line: 1>[1;34m()[0m
[1;32m----> 1[0m cm [38;5;241m=[39m confusion_matrix([43mlabels[49m,clf_new_predict)
[0;32m      2[0m [38;5;28mprint[39m(cm)
[0;32m      4[0m fig,ax[38;5;241m=[39m plt[38;5;241m.[39msubplots()

[1;31mNameError[0m: name 'labels' is not defined
NameError: name 'labels' is not defined

